version: '3'
services:

  flask:
    build:
      dockerfile: Dockerfile
    container_name: flask
    image: konstgav/flask-python:3.9
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: product
      MONGODB_HOSTNAME: mongodb
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
    links: 
      - mongodb

  mongodb:
    image: mongo:4.0.8
    hostname: mongo-host
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: product
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge